In [2]:
import pandas as pd
import numpy as np

In [4]:
goodreads = pd.read_csv(r"C:\Users\melan\Documents\DA8\Projects\capstone\data\clean_goodreads.csv")

In [5]:
goodreads.head()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre
0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,"First published July 29, 2008","Genres, Historical Fiction, Fiction, Romance, ..."
1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,"First published October 25, 2016","Genres, Fiction, Mystery, Thriller, Audiobook,..."
2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,"First published January 10, 2017","Genres, Thriller, Fiction, Action, Military Fi..."
3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,"First published October 11, 2016","Genres, Fiction, Contemporary, Audiobook, Adul..."
4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,"First published August 27, 2012","Genres, Fiction, Contemporary, Audiobook, Humo..."

In [6]:
goodreads.tail()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre
6823,9781538731604,The 18th Abduction,James Patterson,4.10,29983.0,1956.0,"First published April 29, 2019","Genres, Mystery, Fiction, Thriller, Crime, Aud..."
6824,9781420149869,Envious,Lisa Jackson,3.98,2554.0,147.0,"First published March 31, 2020","Genres, Romance, Fiction, Mystery, Contemporar..."
6825,9780525536604,Neon Prey,John Sandford,4.18,21056.0,1592.0,"First published April 23, 2019","Genres, Mystery, Fiction, Thriller, Crime, Mys..."
6826,9781335979957,Denim and Diamonds/A Military Match,Debbie Macomber,3.98,85.0,6.0,"Published March 24, 2020",NaN
6827,9780399181351,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
goodreads.dtypes

isbn                int64
title              object
author             object
avg_rating        float64
count_rating      float64
count_reviews     float64
date_published     object
top_genre          object
dtype: object

In [8]:
goodreads.isnull().sum()

isbn                0
title             179
author            179
avg_rating        179
count_rating      179
count_reviews     179
date_published    179
top_genre         193
dtype: int64

In [ ]:
#delete nulls (will add with self-published df)
goodreads = goodreads.dropna(subset=['title'])

In [ ]:
self_published = pd.read_csv(r"C:\Users\melan\Documents\DA8\Projects\capstone\data\self_published.csv")

In [ ]:
#combine dfs
all_goodreads = pd.concat([goodreads, self_published])

In [11]:
#fix date_published column format
#Remove 'first published' and 'published'

goodreads['date_published'] = goodreads['date_published'].str.replace('First published ', '').str.replace('Published ', '')
goodreads.head()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre
0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,"July 29, 2008","Genres, Historical Fiction, Fiction, Romance, ..."
1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,"October 25, 2016","Genres, Fiction, Mystery, Thriller, Audiobook,..."
2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,"January 10, 2017","Genres, Thriller, Fiction, Action, Military Fi..."
3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,"October 11, 2016","Genres, Fiction, Contemporary, Audiobook, Adul..."
4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,"August 27, 2012","Genres, Fiction, Contemporary, Audiobook, Humo..."

In [12]:
#convert to datetime format
goodreads['date_published'] = pd.to_datetime(goodreads['date_published'], errors='coerce')
goodreads.head()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre
0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,2008-07-29,"Genres, Historical Fiction, Fiction, Romance, ..."
1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,2016-10-25,"Genres, Fiction, Mystery, Thriller, Audiobook,..."
2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,2017-01-10,"Genres, Thriller, Fiction, Action, Military Fi..."
3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,2016-10-11,"Genres, Fiction, Contemporary, Audiobook, Adul..."
4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,2012-08-27,"Genres, Fiction, Contemporary, Audiobook, Humo..."

In [13]:
goodreads[goodreads['date_published'] == 'NaT'].sum()

C:\Users\melan\AppData\Local\Temp\ipykernel_5748\4070747663.py:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  goodreads[goodreads['date_published'] == 'NaT'].sum()

isbn             0.0
title            0.0
author           0.0
avg_rating       0.0
count_rating     0.0
count_reviews    0.0
top_genre        0.0
dtype: float64

In [15]:
#Next need to fix genre column
goodreads['top_genre'][0]

'Genres, Historical Fiction, Fiction, Romance, Historical, World War II, Book Club, War'

In [16]:
#Remove 'Genres ' part
goodreads['top_genre'] = goodreads['top_genre'].str.replace('Genres, ', '')
goodreads.head()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre
0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,2008-07-29,"Historical Fiction, Fiction, Romance, Historic..."
1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,2016-10-25,"Fiction, Mystery, Thriller, Audiobook, Crime, ..."
2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,2017-01-10,"Thriller, Fiction, Action, Military Fiction, S..."
3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,2016-10-11,"Fiction, Contemporary, Audiobook, Adult, Adult..."
4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,2012-08-27,"Fiction, Contemporary, Audiobook, Humor, Adult..."

In [17]:
#Split column into list of genres
genre_list = goodreads['top_genre'].str.split(', ')

In [18]:
goodreads['genre1'] = genre_list.str[0]
goodreads['genre2'] = genre_list.str[1]
goodreads['genre3'] = genre_list.str[2]

In [19]:
goodreads.head()

,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre,genre1,genre2,genre3
0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,2008-07-29,"Historical Fiction, Fiction, Romance, Historic...",Historical Fiction,Fiction,Romance
1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,2016-10-25,"Fiction, Mystery, Thriller, Audiobook, Crime, ...",Fiction,Mystery,Thriller
2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,2017-01-10,"Thriller, Fiction, Action, Military Fiction, S...",Thriller,Fiction,Action
3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,2016-10-11,"Fiction, Contemporary, Audiobook, Adult, Adult...",Fiction,Contemporary,Audiobook
4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,2012-08-27,"Fiction, Contemporary, Audiobook, Humor, Adult...",Fiction,Contemporary,Audiobook

In [20]:
len(goodreads)

6828