In [67]:
import pandas as pd

In [68]:
nyt = pd.read_csv(r"C:\Users\melan\Documents\DA8\Projects\bestseller_capstone\data\merged_dataframe.csv")

In [69]:
nyt.head()

,title,description,contributor,author,contributor_note,price,age_group,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,asterisk,dagger,week,nyt_list,file,month
0,FULL PACKAGE,A man shares a cramped apartment with his frie...,by Lauren Blakely,Lauren Blakely,NaN,0.0,NaN,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,0,0,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
1,THE GUERNSEY LITERARY AND POTATO PEEL PIE SOCIETY,"After World War II, a journalist travels to th...",by Mary Ann Shaffer and Annie Barrows,Mary Ann Shaffer and Annie Barrows,NaN,0.0,NaN,Dial,9780440337973,0440337976,2,0,2,0,0,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
2,THE WHISTLER,A whistleblower alerts a Florida investigator ...,by John Grisham,John Grisham,NaN,0.0,NaN,Doubleday,9780385541206,0385541201,3,4,12,0,0,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
3,RING OF FIRE,"Pike Logan, a member of a secret counterterror...",by Brad Taylor,Brad Taylor,NaN,0.0,NaN,Dutton,9781101984772,None,4,0,1,0,0,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
4,SMALL GREAT THINGS,"A medical crisis entangles a black nurse, a wh...",by Jodi Picoult,Jodi Picoult,NaN,0.0,NaN,Ballantine,9780345544964,034554496X,5,7,9,0,0,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN

In [70]:
#drop contributor_note, price, age_group
nyt = nyt.drop(['contributor', 'contributor_note', 'price', 'age_group', 'asterisk', 'dagger'], axis=1)
nyt.head()

,title,description,author,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,nyt_list,file,month
0,FULL PACKAGE,A man shares a cramped apartment with his frie...,Lauren Blakely,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
1,THE GUERNSEY LITERARY AND POTATO PEEL PIE SOCIETY,"After World War II, a journalist travels to th...",Mary Ann Shaffer and Annie Barrows,Dial,9780440337973,0440337976,2,0,2,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
2,THE WHISTLER,A whistleblower alerts a Florida investigator ...,John Grisham,Doubleday,9780385541206,0385541201,3,4,12,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
3,RING OF FIRE,"Pike Logan, a member of a secret counterterror...",Brad Taylor,Dutton,9781101984772,None,4,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
4,SMALL GREAT THINGS,"A medical crisis entangles a black nurse, a wh...",Jodi Picoult,Ballantine,9780345544964,034554496X,5,7,9,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN

In [71]:
nyt['title'] = nyt['title'].str.title()
nyt.head()

,title,description,author,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,nyt_list,file,month
0,Full Package,A man shares a cramped apartment with his frie...,Lauren Blakely,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
1,The Guernsey Literary And Potato Peel Pie Society,"After World War II, a journalist travels to th...",Mary Ann Shaffer and Annie Barrows,Dial,9780440337973,0440337976,2,0,2,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
2,The Whistler,A whistleblower alerts a Florida investigator ...,John Grisham,Doubleday,9780385541206,0385541201,3,4,12,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
3,Ring Of Fire,"Pike Logan, a member of a secret counterterror...",Brad Taylor,Dutton,9781101984772,None,4,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN
4,Small Great Things,"A medical crisis entangles a black nurse, a wh...",Jodi Picoult,Ballantine,9780345544964,034554496X,5,7,9,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN

In [72]:
len(nyt)

32216

In [73]:
nyt['primary_isbn13'].nunique()

6896

In [74]:
#Add columnn for max weeks on list for each isbn
nyt['max_weeks_on_list'] = nyt.groupby('primary_isbn13')['weeks_on_list'].transform('max')
nyt.head()

,title,description,author,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,nyt_list,file,month,max_weeks_on_list
0,Full Package,A man shares a cramped apartment with his frie...,Lauren Blakely,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN,1
1,The Guernsey Literary And Potato Peel Pie Society,"After World War II, a journalist travels to th...",Mary Ann Shaffer and Annie Barrows,Dial,9780440337973,0440337976,2,0,2,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN,2
2,The Whistler,A whistleblower alerts a Florida investigator ...,John Grisham,Doubleday,9780385541206,0385541201,3,4,12,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN,16
3,Ring Of Fire,"Pike Logan, a member of a secret counterterror...",Brad Taylor,Dutton,9781101984772,None,4,0,1,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN,1
4,Small Great Things,"A medical crisis entangles a black nurse, a wh...",Jodi Picoult,Ballantine,9780345544964,034554496X,5,7,9,2017-01-25,E-Book Fiction,2012to2017_e_book_fiction,NaN,17

In [75]:
nyt.nlargest(1, 'max_weeks_on_list')

,title,description,author,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,nyt_list,file,month,max_weeks_on_list
16022,The Alchemist,A Spanish shepherd boy ventures to Egypt in se...,Paulo Coelho,HarperOne/HarperCollins,9780062315007,0062315005,7,8,427,2017-09-11,Trade Paperback Fiction,2013to2018_trade_paperback_fiction,NaN,427

In [76]:
# Group the DataFrame by the book's identifier and count the occurrences
book_counts = nyt.groupby('title').apply(lambda x: (x['rank'] == 1).sum())

# Find the book with the highest count
most_common_book = book_counts.idxmax()
count = book_counts.loc[most_common_book]

print("The book that appeared most in the #1 spot is:", most_common_book)
print("Number of times in the #1 spot:", count)

The book that appeared most in the #1 spot is: Where The Crawdads Sing
Number of times in the #1 spot: 138

In [77]:
#read in goodreads csv

goodreads = pd.read_csv(r"C:\Users\melan\Documents\DA8\Projects\bestseller_capstone\data\clean_goodreads.csv")

In [78]:
goodreads.head()

,Unnamed: 0,isbn,title,author,avg_rating,count_rating,count_reviews,date_published,top_genre,genre1,genre2,genre3
0,0,9780440337973,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,2008-07-29,"Historical Fiction, Fiction, Romance, Historic...",Historical Fiction,Fiction,Romance
1,1,9780385541206,The Whistler,John Grisham,3.95,120472.0,7710.0,2016-10-25,"Fiction, Mystery, Thriller, Audiobook, Crime, ...",Fiction,Mystery,Thriller
2,2,9781101984772,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,2017-01-10,"Thriller, Fiction, Action, Military Fiction, S...",Thriller,Fiction,Action
3,3,9780345544964,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,2016-10-11,"Fiction, Contemporary, Audiobook, Adult, Adult...",Fiction,Contemporary,Audiobook
4,4,9781476738031,A Man Called Ove,Fredrik Backman,4.38,917052.0,98756.0,2012-08-27,"Fiction, Contemporary, Audiobook, Humor, Adult...",Fiction,Contemporary,Audiobook

In [79]:
len(goodreads)

6828

In [80]:
nyt['primary_isbn13'] = nyt['primary_isbn13'].astype(str)
goodreads['isbn'] = goodreads['isbn'].astype(str)

In [81]:
bestsellers = nyt.merge(goodreads, left_on='primary_isbn13', right_on='isbn', how='left')

In [82]:
bestsellers.head()

,title_x,description,author_x,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,...,title_y,author_y,avg_rating,count_rating,count_reviews,date_published,top_genre,genre1,genre2,genre3
0,Full Package,A man shares a cramped apartment with his frie...,Lauren Blakely,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,2017-01-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Guernsey Literary And Potato Peel Pie Society,"After World War II, a journalist travels to th...",Mary Ann Shaffer and Annie Barrows,Dial,9780440337973,0440337976,2,0,2,2017-01-25,...,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.19,721465.0,60356.0,2008-07-29,"Historical Fiction, Fiction, Romance, Historic...",Historical Fiction,Fiction,Romance
2,The Whistler,A whistleblower alerts a Florida investigator ...,John Grisham,Doubleday,9780385541206,0385541201,3,4,12,2017-01-25,...,The Whistler,John Grisham,3.95,120472.0,7710.0,2016-10-25,"Fiction, Mystery, Thriller, Audiobook, Crime, ...",Fiction,Mystery,Thriller
3,Ring Of Fire,"Pike Logan, a member of a secret counterterror...",Brad Taylor,Dutton,9781101984772,None,4,0,1,2017-01-25,...,Ring of Fire,Brad Taylor,4.28,4371.0,230.0,2017-01-10,"Thriller, Fiction, Action, Military Fiction, S...",Thriller,Fiction,Action
4,Small Great Things,"A medical crisis entangles a black nurse, a wh...",Jodi Picoult,Ballantine,9780345544964,034554496X,5,7,9,2017-01-25,...,Small Great Things,Jodi Picoult,4.35,342790.0,30250.0,2016-10-11,"Fiction, Contemporary, Audiobook, Adult, Adult...",Fiction,Contemporary,Audiobook

In [83]:
bestsellers.columns

Index(['title_x', 'description', 'author_x', 'publisher', 'primary_isbn13',
       'primary_isbn10', 'rank', 'rank_last_week', 'weeks_on_list', 'week',
       'nyt_list', 'file', 'month', 'max_weeks_on_list', 'Unnamed: 0', 'isbn',
       'title_y', 'author_y', 'avg_rating', 'count_rating', 'count_reviews',
       'date_published', 'top_genre', 'genre1', 'genre2', 'genre3'],
      dtype='object')

In [84]:
bestsellers = bestsellers.drop(['title_y', 'author_y', 'Unnamed: 0', 'isbn'], axis=1)
bestsellers = bestsellers.rename(columns={'title_x':'title', 'author_x':'author'})
bestsellers.head()

,title,description,author,publisher,primary_isbn13,primary_isbn10,rank,rank_last_week,weeks_on_list,week,...,month,max_weeks_on_list,avg_rating,count_rating,count_reviews,date_published,top_genre,genre1,genre2,genre3
0,Full Package,A man shares a cramped apartment with his frie...,Lauren Blakely,Lauren Blakely,A00B01MT5HMRV,None,1,0,1,2017-01-25,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Guernsey Literary And Potato Peel Pie Society,"After World War II, a journalist travels to th...",Mary Ann Shaffer and Annie Barrows,Dial,9780440337973,0440337976,2,0,2,2017-01-25,...,NaN,2,4.19,721465.0,60356.0,2008-07-29,"Historical Fiction, Fiction, Romance, Historic...",Historical Fiction,Fiction,Romance
2,The Whistler,A whistleblower alerts a Florida investigator ...,John Grisham,Doubleday,9780385541206,0385541201,3,4,12,2017-01-25,...,NaN,16,3.95,120472.0,7710.0,2016-10-25,"Fiction, Mystery, Thriller, Audiobook, Crime, ...",Fiction,Mystery,Thriller
3,Ring Of Fire,"Pike Logan, a member of a secret counterterror...",Brad Taylor,Dutton,9781101984772,None,4,0,1,2017-01-25,...,NaN,1,4.28,4371.0,230.0,2017-01-10,"Thriller, Fiction, Action, Military Fiction, S...",Thriller,Fiction,Action
4,Small Great Things,"A medical crisis entangles a black nurse, a wh...",Jodi Picoult,Ballantine,9780345544964,034554496X,5,7,9,2017-01-25,...,NaN,17,4.35,342790.0,30250.0,2016-10-11,"Fiction, Contemporary, Audiobook, Adult, Adult...",Fiction,Contemporary,Audiobook

In [85]:
bestsellers.to_csv(r"C:\Users\melan\Documents\DA8\Projects\bestseller_capstone\data\bestsellers_merged.csv")